name: ci

on:
  push:
    branches:
      - master

env:
  OPENCV_VERSION: 4.5.5

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: OPENCV_VERSION=${{ env.OPENCV_VERSION }}
          platforms: linux/arm/v7
          push: true
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/opencv-python:${{ env.OPENCV_VERSION }}-py310,
            ${{ secrets.DOCKERHUB_USERNAME }}/opencv-python:latest
